vim.g.mapleader = " "

vim.keymap.set({ "n", "i" }, "<C-s>", "<cmd>silent w<CR>", { desc = "Save", silent = true })
vim.keymap.set("n", "<leader>q", "<cmd>q<CR>", { desc = "Quit" })
vim.keymap.set("v", "<C-S-c>", "y", { desc = "Copy" })
vim.keymap.set("v", "<C-x>", "d", { desc = "Cut selected text" })
vim.keymap.set("v", ">", ">gv", { desc = "Indent and reselect" })
vim.keymap.set("v", "<", "<gv", { desc = "Outdent and reselect" })
vim.keymap.set("n", "<S-Down>", "<C-d>", { desc = "Scroll down half page" })
vim.keymap.set({ "n", "v", "s" }, "<S-Up>", "<C-u>", { desc = "Scroll up half page" })
vim.keymap.set({ "n", "v", "s" }, "<S-Down>", "<C-d>", { desc = "Scroll down half page" })
vim.keymap.set("i", "<S-Left>", "<C-o>b", { desc = "Jump word left" })
vim.keymap.set("i", "<S-Right>", "<C-o>e", { desc = "Jump word right" })
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>", { desc = "Clear search highlight" })
vim.keymap.set({ "v", "s" }, "<S-Left>", "b", { desc = "Expand selection word left" })
vim.keymap.set({ "v", "s" }, "<S-Right>", "e", { desc = "Expand selection word right" })
vim.keymap.set({ "i", "t" }, "<C-BS>", "<C-w>", { desc = "Delete previous word" })
vim.keymap.set("n", "gi", "<cmd>lua vim.lsp.buf.definition()<CR>", { desc = "Go to definition" })
vim.keymap.set("n", "go", "<C-o>", { desc = "Go back" })
vim.keymap.set("n", "<A-o>", "<C-^>", { desc = "Go to previous file" })

vim.keymap.set("n", "<leader>lf", "<cmd>lua vim.lsp.buf.format()<CR>", { desc = "Format file" })
vim.keymap.set("n", "<leader>ld", "<cmd>lua vim.diagnostic.open_float()<CR>", { desc = "Open diagnostics" })

vim.keymap.set("n", "<leader>e", "<cmd>Oil<CR>", { desc = "Open parent dir" })
vim.keymap.set("n", "<leader>ff", "<cmd>Telescope find_files<CR>", { desc = "Find files" })
vim.keymap.set("n", "<leader>ss", "<cmd>Telescope live_grep<CR>", { desc = "Live grep" })
vim.keymap.set("n", "<leader>gs", "<cmd>Telescope git_status<CR>", { desc = "Git status" })
vim.keymap.set("n", "<leader>gc", "<cmd>Telescope git_commits<CR>", { desc = "Git commits" })
vim.keymap.set("n", "<A-Down>", "<cmd>Gitsigns next_hunk<CR>", { desc = "Next hunk" })
vim.keymap.set("n", "<A-Up>", "<cmd>Gitsigns prev_hunk<CR>", { desc = "Preview hunk" })
vim.keymap.set("n", "<leader>gr", "<cmd>Gitsigns reset_hunk<CR>", { desc = "Reset hunk" })
vim.keymap.set("n", "<leader>gb", "<cmd>Gitsigns blame_line<CR>", { desc = "Show blame line" })
vim.keymap.set({ "n", "i", "t" }, "<A-j>", "<cmd>1ToggleTerm direction=float dir=%:p:h<CR>",
  { desc = "Toggle float terminal" })
