# adding new machines
# nix shell nixpkgs#ssh-to-age -c sh -c 'ssh-to-age -private-key -i /etc/ssh/ssh_host_ed25519_key > /root/.config/sops/age/keys.txt'
# nix shell nixpkgs#ssh-to-age -c ssh-to-age < /etc/ssh/ssh_host_ed25519_key.pub
# sops updatekeys

# desktop: age14rcy5n2urlec4z6avz8q22cw7rchccwst5k57p0rst6hq9y25a6qu60xnp
# laptop: age19h9ghxyscysamz6vlaracmc34v8yttplcs9rwnms5c4nam2rre9qnlx7l5
# server: age1xynqf4y79lhf25hmax64ct0ek553ykpwugkdyzx00r0p5txa84fq3crh2y

creation_rules:
  # common
  - path_regex: hosts/common/.*\.yaml$
    key_groups:
      - age:
          - age14rcy5n2urlec4z6avz8q22cw7rchccwst5k57p0rst6hq9y25a6qu60xnp
          - age19h9ghxyscysamz6vlaracmc34v8yttplcs9rwnms5c4nam2rre9qnlx7l5

  # server
  - path_regex: hosts/server/.*\.yaml$
    key_groups:
      - age:
          - age1xynqf4y79lhf25hmax64ct0ek553ykpwugkdyzx00r0p5txa84fq3crh2y
          - age14rcy5n2urlec4z6avz8q22cw7rchccwst5k57p0rst6hq9y25a6qu60xnp
